# Generated by Django 4.0 on 2022-02-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_survivor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
