# Generated by Django 4.0 on 2022-02-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_survivor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='ammunition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='food',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='medication',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='water',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
