# Generated by Django 4.0 on 2022-02-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_survivor_age_alter_survivor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survivor',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survivor',
            name='report_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
