# Generated by Django 4.0 on 2022-02-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_survivor_gender_alter_survivor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
