# Generated by Django 4.0 on 2022-02-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_survivor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='is_infected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
