# Generated by Django 4.0 on 2022-02-15 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_survivor_is_infected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('serialNumber', models.CharField(max_length=200, unique=True)),
                ('manufacturedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
