# Generated by Django 4.0.2 on 2022-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_robots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='category',
            field=models.CharField(choices=[('Flying', 'Land'), ('Land', 'Land')], max_length=30),
        ),
    ]
